### ISSUE TITLE
FTPStep - add folder instead file

### ISSUE THREAD

**Issue by nicoprida** [jenkinsci/phoenix-autotest-plugin#4]
Could you add or change the sourceFile parameter to allows a folder o just all the files inside a folder?

Maybe something like: foo/*.*

Thanks

**Comment by LinuxSuRen** [comment]
I prefer to put all files into a tar file, then upload it. What do you think?

**Comment by nicoprida** [comment]
In my case, Im using Windows, so if i put all the files into a zip, then I have to unzip into destination and I don't have access to do that.

**Comment by LinuxSuRen** [comment]
But it will cause another problem if the source directory has a very depth level, then it's hard to work. Maybe I could provide a zip and unzip step to implement this.
